В каких случаях происходит выполнение кода в блоке finally﻿?

После завершения блока try, если в нем не было брошено исключение
После завершения обработки пойманного исключения
После завершения блока try, если в нем было брошено исключение, которое не было поймано ни в одном блоке except